# Generated by Django 3.0.1 on 2020-01-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('shows_id', models.AutoField(primary_key=True, serialize=False)),
                ('shows_name', models.CharField(max_length=50)),
                ('shows_description', models.TextField()),
                ('shows_type', models.CharField(max_length=20)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Feedback')),
                ('users', models.ManyToManyField(to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=40)),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Shows')),
            ],
        ),
    ]
